### ISSUE TITLE
Improve error handling 

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/simplesamlphp-module-privacyidea#3]
It is working but errors are misleading and I get apache errors.

Error below is if a user does not exists.

Apache log:

```
[Fri Nov 06 10:06:19.281166 2015] [:error] [pid 17217] [client xxx.xxx.xxx.xxx:55106] PHP Notice:     Trying to get property of non-object in /usr/share/simplesamlphp/modules/privacyidea/lib/Auth/Source/privacyidea.php on line 138, referer: https://www.mydomain.com/simplesampath/module.php/core/loginuserpass.php?
[Fri Nov 06 10:06:19.281199 2015] [:error] [pid 17217] [client xxx.xxx.xxx.xxx:55106] PHP Stack trace:, referer: https://www.mydomain.com/simplesampath/module.php/core/loginuserpass.php?
[Fri Nov 06 10:06:19.281210 2015] [:error] [pid 17217] [client xxx.xxx.xxx.xxx:55106] PHP   1. {main}() /usr/share/simplesamlphp/www/module.php:0, referer: https://www.mydomain.com/simplesampath/module.php/core/loginuserpass.php?
[Fri Nov 06 10:06:19.281219 2015] [:error] [pid 17217] [client xxx.xxx.xxx.xxx:55106] PHP   2. require() /usr/share/simplesamlphp/www/module.php:134, referer: https://www.mydomain.com/simplesampath/module.php/core/loginuserpass.php?
[Fri Nov 06 10:06:19.281236 2015] [:error] [pid 17217] [client xxx.xxx.xxx.xxx:55106] PHP   3. sspmod_core_Auth_UserPassBase::handleLogin() /usr/share/simplesamlphp/modules/core/www/loginuserpass.php:75, referer: https://www.mydomain.com/simplesampath/module.php/core/loginuserpass.php?
[Fri Nov 06 10:06:19.281250 2015] [:error] [pid 17217] [client xxx.xxx.xxx.xxx:55106] PHP   4. sspmod_privacyidea_Auth_Source_privacyidea->login() /usr/share/simplesamlphp/modules/core/lib/Auth/UserPassBase.php:259, referer: https://www.mydomain.com/simplesampath/module.php/core/loginuserpass.php?
```

It seems that Undefined property are not catch in the try block.
So Line 140 is never called.

**Comment by andyboeh** [comment]
I am affected by this and would like to get it fixed. Sometimes, I receive simpleSAMLphp error reports, which is quite annoying. As a quick fix, I did the following in lib/Auth/Source/privacyidea.php, around line 190:
```
if ($status !== True) {
            if(isset($result->error) && isset($result->error->code)) {
                if($result->error->code === 904) {
                    throw new SimpleSAML_Error_Error("WRONGUSERPASS");
                }
            }
            /* We got a valid JSON response, but the STATUS is false */
            throw new SimpleSAML_Error_BadRequest("Valid JSON response, but some internal error occured in privacyidea server.");
        } else {
```
I noticed that error code 904 is set if the user can't be found, so I'm checking for that if the status is not True.
Unfortunately, I don't have the time to properly create a PR for this (and I'm not sure whether it's the right way to fix it), but I'll test it for now.

**Comment by laclaro** [comment]
@NuvandaPV I think this has been fixed in the refactoring, correct?

**Comment by andyboeh** [comment]
It's not fixed for me, I upgrade just a few days ago: If a user doesn't exist, I still get a "Bad request received" message with debug information.

**Comment by NuvandaPV** [comment]
Yep.
